
server:
  port: 3232


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: srivatsan
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
       ddl-auto: update
       naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
 
  application:
    name: invoice-service

logging:
  level:
    org.hibernate.sql:  debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace 
    
    
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"    