
server:
  port: 2626


spring:
  application:
    name: cibile-score-client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka    
    