
server:
  port: 3838


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: srivatsan
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
       ddl-auto: update
       naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
 
  application:
    name: loan-application-service
  boot:
    admin:
      client:
        url:
        - http://localhost:9494

logging:
  level:
    org.hibernate.sql:  debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace 
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka    
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"    